project:
  type: website
  # resources:
  #   - "images/twitter-card.png"
  #   - "course-materials/_slides/"
    
website:
  page-navigation: true
  title: "Quarto NHS Theme"
  author: "Craig Shenton"
  description: "NHS Theme"
  date: now
  site-url: https://craig-shenton.github.io/quarto-nhs-theme
  favicon: _assets/favicon/favicon.ico
  repo-url: https://github.com/craig-shenton/quarto-nhs-theme
  repo-actions: [edit, issue]

  # opengraph: true
  # twitter-card:
  #   creator: "@minebocek"
  #   image: "/images/twitter-card.png"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    background: "#005eb8"
    right:
    - text: "License"
      href: LICENSE.md
    - text: "Code of Conduct"
      href: CODE_OF_CONDUCT.md

  navbar:
    background: "#005eb8"
    logo: _assets/logos/logo-nhs.svg
    align: center
    title: "Quarto NHS Theme"
    collapse-below: lg
 
    right:
      - icon: github
        href: https://github.com/craig-shenton/quarto-nhs-theme
        aria-label: GitHub
      - icon: cloud-fill
        href: https://rstudio.cloud/
        aria-label: RStudio Cloud

    # left:
    #   - text: "Overview"
    #     href: index.qmd
    #   - text: "r-programming"
    #     href: r-programming.qmd
    #   - text: "r-visualisation"
    #     href: r-visualisation.qmd
    #   - text: "p-example"
    #     href: p-example.qmd

  sidebar:
    - id: hello
      title: "Hello!"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
      - text: "Overview"
        href: index.qmd
      - text: "r-programming"
        href: r-programming.qmd
      - text: "r-visualisation"
        href: r-visualisation.qmd
      - text: "p-example"
        href: p-example.qmd

    - id: content
      title: "Content"
      contents:
        - href: index.qmd

    - id: infrastructure
      title: "Infrastructure"
      contents:
        - href: index.qmd

    - id: design
      align: left
      contents:
        - href: index.qmd

format:
  html:
    theme:
      light: [cosmo, _assets/style/dsbox.scss]
      dark: [cosmo, _assets/style/dsbox.scss, _assets/style/dark.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"
    include-in-header: "_assets/style/fontawesome.html"

freeze: auto

editor: visual
