project:
  type: website
  # resources:
  #   - "images/twitter-card.png"
  #   - "course-materials/_slides/"
    
website:
  page-navigation: true
  title: "Quarto NHS Theme"
  author: "Craig Shenton"
  description: "NHS Theme"
  date: now
  site-url: https://craig-shenton.github.io/quarto-nhs-theme
  favicon: _assets/favicon/favicon.ico
  repo-url: https://github.com/craig-shenton/quarto-nhs-theme
  repo-actions: [edit, issue]

  # opengraph: true
  # twitter-card:
  #   creator: "@minebocek"
  #   image: "/images/twitter-card.png"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    background: "#005eb8"
    right:
    - text: "License"
      href: LICENSE.md
    - text: "Code of Conduct"
      href: CODE_OF_CONDUCT.md

  navbar:
    background: "#005eb8"
    logo: _assets/logos/logo-nhs-200.png
    align: center
    title: false
    collapse-below: lg
 
    right:
      - icon: github
        href: https://github.com/craig-shenton/quarto-nhs-theme
        aria-label: GitHub
      - icon: cloud-fill
        href: https://nhs-pycom.net/
        aria-label: NHS Python Community

    left:
      - text: "Quarto NHS Theme"
        href: index.qmd

  sidebar:
    - id: nav
      number-sections: true
      style: "floating"
      collapse-level: 3
      align: left
      contents:
        - section: "Getting Started"
          contents:
            - text: "Introduction" 
              file: index.qmd
        - section: "R"
          contents:
            - text: "R-Language"
              file: r-programming.qmd
            - text: "Data Visualisation"
              file: r-visualisation.qmd
        - section: "Python"
          contents:
            - text: "Python Example"
              file: p-example.qmd
        - section: "Quarto"
          contents:
          - text: "Explore Quarto"
            file: explore.qmd
          - text: "Render vs Preview"
            file: render-vs-preview.qmd
          - text: "Learn More"
            file: learning-more.qmd

format:
  html:
    theme:
      light: [cosmo, _assets/style/dsbox.scss]
      dark: [cosmo, _assets/style/dsbox.scss, _assets/style/dark.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"
    include-in-header: "_assets/style/fontawesome.html"

freeze: auto

editor: visual
